version: '3.11'

services:
  web:
    build: .
    command: bash -c "cd testing && python3 manage.py makemigrations --noinput && python3 manage.py migrate && python3 manage.py generate_questions && python3 manage.py runserver 0.0.0.0:8000"
    #command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
