# Generated by Django 5.0.7 on 2024-07-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
